@echo off
echo Iniciando servidor de desenvolvimento...
echo.
echo Limpando cache...
if exist .next rmdir /s /q .next
echo.
echo Instalando dependencias...
call npm install
echo.
echo Iniciando servidor...
call npm run dev
pause
